### ISSUE TITLE
Differences in hash results..

### ISSUE THREAD

**Issue by jgentes** [diablofong/angular-hmac-sha512#1]
Hi, thanks for writing this module.

I'm trying to understand why I get different results when I create a hash of 'test' here: http://hash.online-convert.com/sha512-generator (this outputs 'ee26b0dd4af7e749aa1a8ee3c10ae9923f618980772e473f8819a5d4940e0db27ac185f8a0e1d5f84f88bc887fd67b143732c304cc5fa9ad8e6f57f50028a8ff')

And with your module, which produces this for 'test': '29c5fab077c009b9e6676b2f082a7ab3b0462b41acf75f075b5a7bac5619ec81c9d8bb2e25b6d33800fba279ee492ac7d05220e829464df3ca8e00298c517764'

In my use case, the first result matches the source I'm trying to match, and the second does not.

Any ideas?

**Comment by diablofong** [comment]
Hi @jgentes, I think the result is different with the algorithm, This module uses algorithm method for the CryptoJS, But I don't know hash.online-convert this site uses encrypt algorithm, So I hope my answer can help you :)

**Comment by jgentes** [comment]
Thanks, I ended up loading CryptoJS directly into Angular and hashing it that way, and the result came out correctly (as matching the online-convert generator).
